### ISSUE TITLE
component height is expanding more than the screen height

### ISSUE THREAD

**Issue by ayush-AI** [piyushmishra1416/side-panel#3]
Right now the component height is expanding more than the screen height this should not be case. According to me the best approach would be to make the height as auto and set the min height to the 100% or 100vh. Making the height auto will be useful when the number of layouts will be in large number. So the user will be able to scroll through all of the layouts.

**Comment by piyushmishra1416** [comment]
Okay! and can I use the react.fragment instead of divs

**Comment by ayush-AI** [comment]
> Okay! and can I use the react.fragment instead of divs

It depends on when you need a styled container go for div otherwise go for fragments

**Comment by piyushmishra1416** [comment]
Also, can you elaborate on this issue as the panel is working properly?

**Comment by ayush-AI** [comment]
Yup, now this issue is fixed so we can close this.
